// <auto-generated />
namespace ToplantiTakip.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cc8 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cc8));
        
        string IMigrationMetadata.Id
        {
            get { return "201811231900205_cc8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
